default: &global
  adapter: mysql
  encoding: utf8
  pool: 5
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *global
  database: webstripe_development

test:
  <<: *global
  database: webstripe_test

